### ISSUE TITLE
Package 'dfpk' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/ExperimentalDesign#25]
Package [dfpk](https://CRAN.R-project.org/package=dfpk) is currently listed in CRAN Task View [ExperimentalDesign](https://CRAN.R-project.org/view=ExperimentalDesign) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by tylermorganwall** [comment]
Email sent to maintainer asking about their intention to fix and re-upload to CRAN.

**Comment by tylermorganwall** [comment]
Maintainer said they intend to fix the issue and re-upload the package to CRAN.

**Comment by ugroempi** [comment]
:thumbsup:

**Comment by tylermorganwall** [comment]
I removed `dfpk` from the task view (425d1b756e8cfdb3f63b994e83ec10e3bc501f50) due to a lack of action from the maintainer.
