### ISSUE TITLE
Package 'OptGS' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by kurthornik** [cran-task-views/ExperimentalDesign#27]
Package [OptGS](https://CRAN.R-project.org/package=OptGS) is currently listed in CRAN Task View [ExperimentalDesign](https://CRAN.R-project.org/view=ExperimentalDesign) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.  See the section on _CRAN package archivals_ in the [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md) for more details.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by tylermorganwall** [comment]
Email sent to maintainers asking about the intention to re-upload to CRAN.

**Comment by tylermorganwall** [comment]
Maintainer indicated they intend to fix and upload with the next few weeks.

**Comment by tylermorganwall** [comment]
OptGS is now back on the CRAN.
